### PR TITLE
Fix link for config options in README

### PR DESCRIPTION
**Pull request by jmeridth**
- seems tinymce updated their site, link was broken
- the old link can be found at http://archive.tinymce.com/wiki.php/Controls if you prefer that option

### CODE REVIEW

**Comment by spohlenz** [comment]
Thanks for letting me know. While not an exact match to the previous page, it seem like https://www.tinymce.com/docs/configure/ might be a better fit for the link target, since each sub-page goes into detail about each of the available options (and not just the toolbar options). What do you think?

**Comment by jmeridth** [comment]
@spohlenz I'm still leaning towards my suggestion only because as a first-time user, in the context of where the link is in the README, they just want to know what other config options can go into `config/tinymce.yml` file. Exactly like I did :smile: This allows them (and myself) to get up and running quicker.  Maybe a second link to the docs in general afterwards or before?

From https://www.tinymce.com/docs/configure/ the user would have to click `Explore Advanced Topics` in the left menu and then `Editor Control Identifiers`.  That is not intuitive for first-time users.

wdyt?

**Comment by spohlenz** [comment]
The documentation is a bit more confusing now, but it looks like the _Editor Control Identifiers_ page is just the toolbar/menu options, whereas the subpages of the _Configure_ section go into detail on all of the configuration options that are available, each of which can be configured in `tinymce.yml`.

It's unfortunate that there doesn't seem to a list of all of the options on one page anymore, but I'm still inclined towards https://www.tinymce.com/docs/configure/ being the best fit.

**Comment by jmeridth** [comment]
@spohlenz link changed to match your request.  I agree, with all of those options being available, the general link is better.  Cheers.  :beers:

**Comment by spohlenz** [comment]
Merged. Thank you.

**Pull request merged**
